category = Category.find_by(value:"appliances")
[
  "Stainless Steel French Door Refrigerator",
  "Front Load Smart Washing Machine (High Efficiency)",
  "Electric Dryer (with Sensor Dry)",
  "Gas Range with Convection Oven and Air Fry",
  "Built-in Dishwasher (Quiet Operation, Stainless Steel Tub)",
  "Over-the-Range Microwave Oven (with Sensor Cooking)",
  "Countertop Toaster Oven (6-Slice, Broil Function)",
  "Programmable Coffee Maker (12-Cup, Thermal Carafe)",
  "Semi-Automatic Espresso Machine (with Milk Frother)",
  "High-Powered Blender (with Smoothie Cup)",
  "12-Cup Food Processor (with Multiple Blades)",
  "Tilt-Head Stand Mixer (5-Quart, Multiple Speeds)",
  "5-Speed Hand Mixer (with Storage Case)",
  "Variable Temperature Electric Kettle (Stainless Steel)",
  "7-Quart Slow Cooker (Programmable)",
  "Multi-Function Rice Cooker (with Steamer Basket)",
  "Electric Pressure Cooker (6-Quart, Multi-Function)",
  "Digital Air Fryer (Large Capacity)",
  "Belgian Waffle Maker (Non-Stick)",
  "Programmable Bread Maker (with Gluten-Free Setting)",
  "Compressor Ice Cream Maker (2-Quart)",
  "Centrifugal Juicer (Wide Feed Chute)",
  "Food Dehydrator (with Multiple Trays)",
  "Vacuum Sealer (with Starter Kit)",
  "Water Filter Pitcher (10-Cup)",
  "Continuous Feed Garbage Disposal (3/4 HP)",
  "Dual Zone Wine Refrigerator (24-Bottle Capacity)",
  "Compact Mini Fridge (with Freezer Compartment)",
  "Chest Freezer (7 Cubic Feet)",
  "Upright Freezer (Frost-Free)",
  "Portable Air Conditioner (12,000 BTU)",
  "Window Air Conditioner (8,000 BTU, with Remote)",
  "Ceramic Space Heater (with Thermostat)",
  "Cool Mist Humidifier (Ultrasonic)",
  "Large Capacity Dehumidifier (with Auto Shut-Off)",
  "HEPA Filter Air Purifier (for Large Rooms)",
  "Professional Steam Iron (with Auto Shut-Off)",
  "Handheld Garment Steamer (Portable)",
  "Computerized Sewing Machine (with Multiple Stitch Options)",
  "Cordless Stick Vacuum Cleaner (with HEPA Filter)",
  "Robot Vacuum Cleaner (with Smart Mapping)",
  "Tankless Electric Water Heater (On-Demand)",
  "Under Cabinet Range Hood (Stainless Steel)",
  "Microwave with Grill Function and Convection",
  "Deep Fryer (with Basket and Timer)",
  "Sandwich Maker (with Removable Plates)",
  "Electric Popcorn Maker (Hot Air)",
  "Automatic Yogurt Maker (with Glass Jars)",
  "Electric Griddle (with Non-Stick Surface)",
  "Food Steamer (Multi-Tiered)"
].each do |name|
  Catelogue.find_or_create_by!(name: name, category: category )
end