category = Category.find_by(value: "baby_products")
[
  "Infant Car Seat (Rear-Facing)",
  "Convertible Car Seat (Rear and Forward-Facing)",
  "Booster Car Seat (High-Back)",
  "Stroller (Full-Size)",
  "Stroller (Lightweight/Umbrella)",
  "Travel System (Stroller and Car Seat Combo)",
  "Jogging Stroller",
  "Double Stroller (Side-by-Side)",
  "Double Stroller (Tandem)",
  "Baby Carrier (Wrap)",
  "Baby Carrier (Structured)",
  "Baby Carrier (Hip Seat)",
  "Crib (Standard)",
  "Crib (Convertible, 4-in-1)",
  "Bassinet (Bedside Sleeper)",
  "Portable Crib/Playard",
  "Changing Table (with Storage)",
  "Changing Pad",
  "Diaper Pail (Odor-Control)",
  "Diaper Bag (Backpack)",
  "Diaper Bag (Tote)",
  "Baby Monitor (Video)",
  "Baby Monitor (Audio)",
  "Baby Monitor (Movement Sensor)",
  "White Noise Machine (Sound Machine)",
  "Baby Swing (Electric)",
  "Bouncer Seat (Vibrating)",
  "Activity Gym/Play Mat",
  "High Chair (with Adjustable Height)",
  "High Chair (Convertible)",
  "Booster Seat (for Dining Table)",
  "Baby Food Maker",
  "Bottle Warmer",
  "Bottle Sterilizer",
  "Breast Pump (Electric, Double)",
  "Breast Pump (Manual)",
  "Nursing Pillow",
  "Baby Bottles (Anti-Colic)",
  "Pacifiers (Newborn)",
  "Pacifiers (Orthodontic)",
  "Teethers (Silicone)",
  "Baby Clothes (Onesies, Sleepers)",
  "Baby Clothes (Swaddle Blankets)",
  "Baby Bathtub",
  "Baby Washcloths",
  "Baby Shampoo & Body Wash",
  "Baby Lotion",
  "Diaper Rash Cream",
  "Baby Thermometer (Rectal/Forehead)",
  "Nail Clippers (Baby)"
].each do |name|
  Catelogue.find_or_create_by(name: name, category: category)
end