category = Category.find_by(value: "books")

[
  "The Lord of the Rings",
  "Pride and Prejudice",
  "To Kill a Mockingbird",
  "1984",
  "The Great Gatsby",
  "One Hundred Years of Solitude",
  "The Catcher in the Rye",
  "Beloved",
  "The Hobbit",
  "Little Women",
  "Fahrenheit 451",
  "Jane Eyre",
  "Gone with the Wind",
  "The Diary of a Young Girl",
  "Animal Farm",
  "Lord of the Flies",
  "The Book Thief",
  "The Grapes of Wrath",
  "The Color Purple",
  "Brave New World",
  "Crime and Punishment",
  "Wuthering Heights",
  "The Odyssey",
  "The Iliad",
  "Moby Dick",
  "Frankenstein",
  "Don Quixote",
  "Hamlet",
  "The Adventures of Huckleberry Finn",
  "Alice's Adventures in Wonderland",
  "A Tale of Two Cities",
  "Anna Karenina",
  "The Count of Monte Cristo",
  "Les Misérables",
  "The Picture of Dorian Gray",
  "Slaughterhouse-Five",
  "The Stranger",
  "A Christmas Carol",
  "The Handmaid's Tale",
  "Catch-22",
  "And Then There Were None",
  "The Hitchhiker's Guide to the Galaxy",
  "The Girl with the Dragon Tattoo",
  "Dune",
  "A Game of Thrones",
  "The Hunger Games",
  "Harry Potter and the Sorcerer's Stone",
  "The Da Vinci Code",
  "The Alchemist",
    "Sapiens: A Brief History of Humankind"
].each do |name|
  Catelogue.find_or_create_by(name: name, category: category)
end