category = Category.find_by(value: "cosmetics")

[
    "Liquid Foundation (Full Coverage)",
    "Tinted Moisturizer (Light Coverage)",
    "BB Cream",
    "CC Cream",
    "Concealer (Cream, Stick)",
    "Concealer (Liquid)",
    "Setting Powder (Loose)",
    "Setting Powder (Pressed)",
    "Face Primer (Pore Minimizing)",
    "Face Primer (Hydrating)",
    "Color Corrector (Green - Redness)",
    "Color Corrector (Peach - Dark Circles)",
    "Bronzer (Powder)",
    "Bronzer (Cream)",
    "Blush (Powder, Warm Tone)",
    "Blush (Powder, Cool Tone)",
    "Blush (Cream)",
    "Highlighter (Powder)",
    "Highlighter (Liquid)",
    "Highlighter (Cream Stick)",
    "Contour Palette (Powder)",
    "Contour Stick (Cream)",
    "Eyeshadow Palette (Neutral Tones)",
    "Eyeshadow Palette (Bold Colors)",
    "Eyeshadow Primer",
    "Single Eyeshadow (Matte)",
    "Single Eyeshadow (Shimmer)",
    "Eyeliner (Pencil, Black)",
    "Eyeliner (Pencil, Brown)",
    "Eyeliner (Liquid, Black)",
    "Eyeliner (Gel)",
    "Mascara (Volumizing, Black)",
    "Mascara (Lengthening, Black)",
    "Mascara (Waterproof)",
    "Eyebrow Pencil",
    "Eyebrow Gel (Tinted)",
    "Eyebrow Pomade",
    "Lipstick (Matte, Red)",
    "Lipstick (Satin, Nude)",
    "Lipstick (Cream, Pink)",
    "Lip Gloss (Clear)",
    "Lip Gloss (Shimmer)",
    "Lip Liner (Nude)",
    "Lip Liner (Red)",
     "Lip Stain",
    "Lip Balm (Tinted)",
    "Lip Balm (SPF)",
    "Setting Spray (Matte Finish)",
    "Setting Spray (Dewy Finish)",
    "Makeup Remover Wipes"
].each do |name|
  Catelogue.find_or_create_by(name: name, category: category)
end