category = Category.find_by(value: "electronics")

[
    "Smartphone (Flagship Model)",
    "Smartphone (Mid-Range)",
    "Laptop (Gaming, High Performance)",
    "Laptop (Ultrabook, Thin and Light)",
    "Laptop (2-in-1, Convertible)",
    "Tablet (10-inch, Android)",
    "Tablet (12-inch, with Pen Support)",
    "Smart TV (4K, OLED, 55-inch)",
    "Smart TV (4K, QLED, 65-inch)",
    "Soundbar (with Wireless Subwoofer)",
    "Home Theater System (5.1.2 Surround Sound)",
    "Wireless Headphones (Over-Ear, Noise-Canceling)",
    "Wireless Earbuds (True Wireless, Noise-Canceling)",
    "Bluetooth Speaker (Portable, Waterproof)",
    "Bluetooth Speaker (Smart, with Voice Assistant)",
    "Gaming Console (Next-Gen, Disc Version)",
    "Gaming Console (Next-Gen, Digital Edition)",
    "Gaming PC (High-End, Prebuilt)",
    "Gaming Monitor (144Hz, 1ms Response Time)",
    "Curved Gaming Monitor (Ultrawide)",
    "VR Headset (Standalone)",
    "VR Headset (PC-Connected)",
    "Digital Camera (DSLR, Full-Frame)",
    "Mirrorless Camera (APS-C Sensor)",
    "Action Camera (4K, Waterproof)",
    "Drone (with 4K Camera, GPS)",
    "Smartwatch (with Fitness Tracking, GPS)",
    "Fitness Tracker (Band, Heart Rate Monitor)",
    "E-Reader (with Backlight, Waterproof)",
    "External Hard Drive (4TB, Portable)",
    "Solid State Drive (SSD, 1TB, NVMe)",
    "USB Flash Drive (256GB, USB 3.2)",
    "Wireless Router (Wi-Fi 6E)",
    "Mesh Wi-Fi System (3-Pack)",
    "Computer Monitor (27-inch, 4K)",
    "Keyboard (Mechanical, RGB Backlighting)",
    "Mouse (Gaming, Wireless)",
    "Mouse (Ergonomic, Vertical)",
    "Webcam (1080p, with Microphone)",
    "Microphone (USB, Condenser)",
    "Graphics Card (High-End, Latest Generation)",
    "RAM (32GB, DDR5)",
    "Power Supply Unit (PSU, 850W, Gold Rated)",
    "Computer Case (Mid-Tower, with RGB Fans)",
    "CPU Cooler (Liquid, AIO)",
    "Portable Power Bank (20000mAh, Fast Charging)",
    "Wireless Charging Pad (Fast Charging)",
    "Surge Protector (with USB Ports)",
    "Cable Management Box",
    "Smart Home Hub (Voice Control)"
].each do |name|
  Catelogue.find_or_create_by(name: name, category: category)
end