category = Category.find_by(value: "furniture")

[
  "Sectional Sofa (L-Shaped, Fabric)",
  "Sectional Sofa (U-Shaped, Leather)",
  "Sofa (Three-Seater, Mid-Century Modern)",
  "Loveseat (Two-Seater, Velvet)",
  "Recliner Chair (Leather, Power Lift)",
  "Armchair (Accent Chair, Fabric)",
  "Coffee Table (Rectangular, Wood)",
  "Coffee Table (Round, Glass Top)",
  "Coffee Table (Lift-Top, with Storage)",
  "End Table (Set of 2, Metal)",
  "End Table (with Charging Station)",
  "TV Stand (with Storage, for 65-inch TV)",
  "TV Stand (Floating, Wall-Mounted)",
  "Bookshelf (Tall, 5-Tier)",
  "Bookshelf (Ladder Style, Leaning)",
  "Dining Table (Rectangular, Extendable)",
  "Dining Table (Round, Pedestal)",
  "Dining Chairs (Set of 4, Upholstered)",
  "Dining Chairs (Set of 2, Metal)",
  "Bar Stools (Counter Height, Set of 2)",
  "Bar Stools (Adjustable Height, Swivel)",
  "Kitchen Island (with Storage, Butcher Block Top)",
  "Bed Frame (Queen Size, Platform)",
  "Bed Frame (King Size, with Headboard)",
  "Bed Frame (Full Size, Metal)",
  "Mattress (Queen Size, Memory Foam)",
  "Mattress (King Size, Hybrid)",
  "Nightstand (with Drawer, Wood)",
  "Nightstand (with Charging Station, USB Ports)",
  "Dresser (6-Drawer, Wide)",
  "Dresser (5-Drawer, Tall)",
  "Chest of Drawers (Vertical)",
  "Wardrobe/Armoire (with Mirror, Sliding Doors)",
  "Desk (Computer Desk, with Hutch)",
  "Desk (Standing Desk, Electric)",
  "Office Chair (Ergonomic, Mesh Back)",
  "Office Chair (Executive, Leather)",
  "Filing Cabinet (2-Drawer, Locking)",
  "Filing Cabinet (Lateral, Wide)",
  "Ottoman (Storage Ottoman, Rectangular)",
  "Ottoman (Round, Pouf)",
  "Entryway Bench (with Shoe Storage)",
  "Coat Rack (Wall-Mounted, with Hooks)",
  "Coat Rack (Free-Standing)",
  "Mirror (Full-Length, Floor Mirror)",
  "Mirror (Wall-Mounted, Decorative)",
  "Console Table (Narrow, Entryway)",
  "Room Divider (Folding Screen, 4-Panel)",
  "Futon (Convertible Sofa Bed)"
].each do |name|
  Catelogue.find_or_create_by(name: name, category: category)
end