category = Category.find_by(value: "garden_and_outdoors")

[
  "Patio Dining Set (Table and 6 Chairs)",
  "Outdoor Sectional Sofa (with Cushions)",
  "Adirondack Chair (Set of 2)",
  "Chaise Lounge Chair (Outdoor, Adjustable)",
  "Hammock (with Stand)",
  "Porch Swing (with Canopy)",
  "Outdoor Rug (Weather-Resistant)",
  "Patio Umbrella (with Base)",
  "Outdoor String Lights (LED, Solar-Powered)",
  "Fire Pit (Wood-Burning)",
  "Fire Pit (Propane)",
  "Outdoor Heater (Propane, Standing)",
  "Gas Grill (4-Burner, with Side Burner)",
  "Charcoal Grill (Kettle)",
  "Smoker (Electric)",
  "Pizza Oven (Outdoor)",
  "Lawn Mower (Gas-Powered)",
  "Lawn Mower (Electric, Cordless)",
  "String Trimmer/Edger (Gas)",
  "String Trimmer/Edger (Electric, Cordless)",
  "Hedge Trimmer (Electric)",
  "Leaf Blower (Gas)",
  "Leaf Blower (Electric, Cordless)",
  "Pressure Washer (Electric)",
  "Garden Hose (Expandable)",
  "Garden Hose Reel (with Storage)",
  "Sprinkler (Oscillating)",
  "Watering Can",
  "Garden Tools Set (Hand Trowel, Cultivator, etc.)",
  "Pruning Shears",
  "Loppers",
  "Garden Gloves (Heavy-Duty)",
  "Wheelbarrow",
  "Raised Garden Bed (Cedar)",
  "Potting Bench",
  "Planter Box (Rectangular)",
  "Hanging Planter",
  "Plant Stand",
  "Garden Trellis",
  "Compost Bin",
  "Rain Barrel",
  "Bird Feeder",
  "Bird Bath",
  "Outdoor Fountain",
  "Garden Gnomes (Set)",
  "Solar Garden Lights (Path Lights)",
  "Insect Repellent (Citronella Candles)",
  "Sunscreen (SPF 30, for Outdoor Use)",
  "Bug Zapper",
  "Cooler (Rolling, Large Capacity)",
  "Camping Tent (4-Person)"
].each do |name|
  Catelogue.find_or_create_by(name: name, category: category)
end