category = Category.find_by(value: "health_and_personal_care")

[
  "Electric Toothbrush (with Multiple Modes)",
  "Toothbrush Heads (Replacement, Soft Bristles)",
  "Toothpaste (Whitening)",
  "Toothpaste (for Sensitive Teeth)",
  "Mouthwash (Antiseptic)",
  "Dental Floss (Waxed)",
  "Dental Floss (Unwaxed)",
  "Floss Picks",
  "Water Flosser",
  "Teeth Whitening Strips",
  "Teeth Whitening Kit (with LED Light)",
  "Shampoo (Volumizing)",
  "Shampoo (for Dry Scalp)",
  "Conditioner (Moisturizing)",
  "Conditioner (Leave-In)",
  "Hair Styling Gel",
  "Hair Spray (Strong Hold)",
  "Dry Shampoo",
  "Body Wash (Moisturizing)",
  "Body Wash (Exfoliating)",
  "Bar Soap (Natural, Unscented)",
  "Body Lotion (for Dry Skin)",
  "Body Lotion (with SPF)",
  "Hand Soap (Antibacterial)",
  "Hand Sanitizer (Gel)",
  "Sunscreen (SPF 50, Broad Spectrum)",
  "Facial Cleanser (Gentle)",
  "Facial Cleanser (for Acne-Prone Skin)",
  "Facial Toner",
  "Facial Moisturizer (with Hyaluronic Acid)",
  "Facial Serum (Vitamin C)",
  "Eye Cream",
  "Face Mask (Sheet Mask)",
  "Face Mask (Clay Mask)",
  "Exfoliating Scrub (Facial)",
  "Makeup Remover (Micellar Water)",
  "Cotton Pads",
  "Cotton Swabs",
  "Razor (for Men, 5-Blade)",
  "Razor (for Women, with Moisturizing Strip)",
  "Shaving Cream (for Sensitive Skin)",
  "Aftershave Balm",
  "Deodorant (Antiperspirant)",
  "Deodorant (Natural)",
  "Pain Reliever (Ibuprofen)",
  "Pain Reliever (Acetaminophen)",
  "Allergy Medication (Antihistamine)",
  "Multivitamin (for Adults)",
  "Vitamin D Supplements",
    "First Aid Kit"
].each do |name|
  Catelogue.find_or_create_by(name: name, category: category)
end