category = Category.find_by(value: "music")

[
  "Acoustic Guitar (Dreadnought)",
  "Acoustic Guitar (Classical, Nylon Strings)",
  "Electric Guitar (Solid Body, Stratocaster Style)",
  "Electric Guitar (Hollow Body, Archtop)",
  "Bass Guitar (4-String, Electric)",
  "Bass Guitar (5-String, Electric)",
  "Ukulele (Soprano)",
  "Ukulele (Concert)",
  "Mandolin (A-Style)",
  "Banjo (5-String)",
  "Violin (4/4 Size, Full Size)",
  "Cello (4/4 Size, Full Size)",
  "Keyboard (Digital Piano, 88 Weighted Keys)",
  "Keyboard (Synthesizer, Workstation)",
  "MIDI Controller Keyboard (49-Key)",
  "Drum Set (Acoustic, 5-Piece)",
  "Drum Set (Electronic, with Mesh Heads)",
  "Cymbals (Set, Hi-Hat, Crash, Ride)",
  "Drumsticks (5A, Wood Tip)",
  "Guitar Amplifier (Combo Amp, Tube)",
  "Guitar Amplifier (Solid State, Practice Amp)",
  "Bass Amplifier (Combo Amp)",
  "Microphone (Dynamic, Vocal)",
  "Microphone (Condenser, Studio)",
  "Audio Interface (USB, 2-Input)",
  "Headphones (Studio, Closed-Back)",
  "Headphones (Open-Back, for Mixing)",
  "Studio Monitors (Pair, Nearfield)",
  "PA System (Portable, with Mixer)",
  "Guitar Pedal (Overdrive)",
  "Guitar Pedal (Delay)",
  "Guitar Pedal (Reverb)",
  "Guitar Tuner (Clip-On)",
  "Guitar Strings (Acoustic, Light Gauge)",
  "Guitar Strings (Electric, Regular Gauge)",
  "Guitar Strap",
  "Guitar Picks (Variety Pack)",
  "Guitar Case (Hardshell)",
  "Guitar Case (Gig Bag)",
  "Music Stand",
  "Sheet Music (Beginner Guitar Method Book)",
  "Sheet Music (Piano, Classical)",
  "Sheet Music (Pop Songs)",
  "Metronome (Digital)",
  "Ear Plugs (for Musicians)",
  "Microphone Stand",
  "XLR Cable (Microphone Cable)",
  "Instrument Cable (1/4-inch)",
  "DJ Controller",
  "Vinyl Turntable"
].each do |name|
  Catelogue.find_or_create_by(name: name, category: category)
end