category = Category.find_by(value: "toys")

[
  "Building Blocks (Large Set, Plastic)",
  "Building Blocks (Wooden, Classic)",
  "LEGO Set (City Theme)",
  "LEGO Set (Star Wars Theme)",
  "Play-Doh Set (with Tools and Molds)",
  "Art Supplies (Crayons, Markers, Paper, Paint)",
  "Coloring Book (Animals)",
  "Coloring Book (Princesses)",
  "Stuffed Animal (Teddy Bear)",
  "Stuffed Animal (Unicorn)",
  "Stuffed Animal (Dog)",
  "Doll (Fashion Doll, with Accessories)",
  "Doll (Baby Doll, with Bottle)",
  "Dollhouse (with Furniture)",
  "Action Figure (Superhero)",
  "Action Figure (Dinosaur)",
  "Toy Cars (Die-Cast, Set of 5)",
  "Toy Train Set (Wooden, with Track)",
  "Toy Train Set (Electric, with Remote)",
  "Remote Control Car (Off-Road)",
  "Remote Control Helicopter",
  "Puzzle (Jigsaw, 100 Pieces)",
  "Puzzle (Jigsaw, 500 Pieces)",
  "Board Game (Family, Strategy)",
  "Board Game (Children's, Classic)",
  "Card Game (Matching)",
  "Card Game (Educational)",
  "Play Kitchen Set (with Accessories)",
  "Toy Food (Wooden, Cutting Set)",
  "Toy Cash Register (with Play Money)",
  "Doctor Kit (Toy, with Stethoscope)",
  "Tool Set (Toy, with Hammer, Saw)",
  "Science Kit (Volcano Experiment)",
  "Science Kit (Crystal Growing)",
  "Outdoor Toy (Swing Set)",
  "Outdoor Toy (Slide)",
  "Ride-On Toy (Car, Foot-Powered)",
  "Tricycle (with Push Handle)",
  "Scooter (Kick Scooter)",
  "Bicycle (with Training Wheels)",
  "Ball (Soccer Ball)",
  "Ball (Basketball)",
  "Jump Rope",
  "Hula Hoop",
  "Bubble Blower (Automatic)",
  "Water Gun (Large)",
  "Sand Toys (Bucket, Shovel, Molds)",
  "Kite (Easy to Fly)",
  "Plush Toy (Character)",
  "Educational Toy (Learning Tablet)"
].each do |name|
  Catelogue.find_or_create_by(name: name, category: category)
end