category = Category.find_by(value: "video_games")

[
  "The Legend of Zelda: Tears of the Kingdom (Switch)",
  "Elden Ring (PS5, Xbox Series X/S, PC)",
  "God of War Ragnarök (PS5, PS4)",
  "Horizon Forbidden West (PS5, PS4)",
  "Starfield (Xbox Series X/S, PC)",
  "Marvel's Spider-Man 2 (PS5)",
  "Final Fantasy XVI (PS5)",
  "Resident Evil 4 Remake (PS5, Xbox Series X/S, PC, PS4)",
  "Street Fighter 6 (PS5, Xbox Series X/S, PC, PS4)",
  "Diablo IV (PS5, Xbox Series X/S, PC, PS4, Xbox One)",
  "Hogwarts Legacy (PS5, Xbox Series X/S, PC, PS4, Xbox One, Switch)",
  "Cyberpunk 2077 (PS5, Xbox Series X/S, PC, PS4, Xbox One)",
  "Assassin's Creed Mirage (PS5, Xbox Series X/S, PC, PS4, Xbox One)",
  "Mortal Kombat 1 (PS5, Xbox Series X/S, PC, Switch)",
  "Forza Motorsport (Xbox Series X/S, PC)",
  "Alan Wake 2 (PS5, Xbox Series X/S, PC)",
  "Baldur's Gate 3 (PC, PS5)",
  "Super Mario Bros. Wonder (Switch)",
  "Metroid Prime Remastered (Switch)",
  "Dead Space Remake (PS5, Xbox Series X/S, PC)",
  "Lies of P (PS5, Xbox Series X/S, PC, PS4, Xbox One)",
  "Star Wars Jedi: Survivor (PS5, Xbox Series X/S, PC)",
  "Armored Core VI: Fires of Rubicon (PS5, Xbox Series X/S, PC, PS4, Xbox One)",
  "Persona 5 Royal (PS5, Xbox Series X/S, PC, Switch, PS4, Xbox One)",
  "Ghost of Tsushima: Director's Cut (PS5, PS4)",
  "Death Stranding: Director's Cut (PS5, PC)",
  "Demon's Souls (PS5)",
  "Ratchet & Clank: Rift Apart (PS5)",
  "Returnal (PS5)",
  "Gran Turismo 7 (PS5, PS4)",
  "The Last of Us Part I (PS5, PC)",
  "Red Dead Redemption 2 (PS4, Xbox One, PC)",
  "Grand Theft Auto V (PS5, Xbox Series X/S, PS4, Xbox One, PC)",
  "The Witcher 3: Wild Hunt - Complete Edition (PS5, Xbox Series X/S, PC, PS4, Xbox One, Switch)",
  "Minecraft (Various Platforms)",
  "Fortnite (Various Platforms)",
  "Call of Duty: Modern Warfare III (Various Platforms)",  
  "Apex Legends (Various Platforms)",
  "Overwatch 2 (Various Platforms)",
  "League of Legends (PC)",
  "Dota 2 (PC)",
  "Valorant (PC)",
  "Counter-Strike: Global Offensive (PC)",
  "Among Us (Various Platforms)",
  "Fall Guys (Various Platforms)",
  "Roblox (Various Platforms)",
  "Animal Crossing: New Horizons (Switch)",
  "Mario Kart 8 Deluxe (Switch)",
  "Super Smash Bros. Ultimate (Switch)",
  "Pokemon Scarlet/Violet (Switch)"
].each do |name|
  Catelogue.find_or_create_by(name: name, category: category)
end